In [56]:
import pandas as pd 
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_digits

In [57]:
digits = load_digits()

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(digits.data,digits.target,test_size=0.3)

In [59]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)


C:\Users\youne\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [60]:
Sv = SVC()
Sv.fit(X_train,y_train)
Sv.score(X_test,y_test)

0.9814814814814815

In [61]:
Rf = RandomForestClassifier()
Rf.fit(X_train,y_train)
Rf.score(X_test,y_test)

0.9703703703703703

In [62]:
from sklearn.model_selection import KFold
KF = KFold(n_splits = 3)
KF


KFold(n_splits=3, random_state=None, shuffle=False)

In [63]:

for train_index,test_index in KF.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)
    

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [64]:
def get_score(model,X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test ,y_test)

In [65]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9814814814814815

In [66]:
from sklearn.model_selection import StratifiedKFold

# Now you can use StratifiedKFold
folds = StratifiedKFold(n_splits=3)


In [70]:
score_lr = []
score_svc= []
score_rf= []
for train_index,test_index in KF.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index],  digits.target[train_index],digits.target[test_index]
    score_lr.append(get_score(LogisticRegression(),X_train, X_test, y_train, y_test))
    score_svc.append(get_score(SVC(),X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(),X_train, X_test, y_train, y_test))
    
    


C:\Users\youne\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\youne\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [71]:
# Display the scores
print("Logistic Regression Scores:", score_lr)
print("SVM Scores:", score_svc)
print("Random Forest Scores:", score_rf)

Logistic Regression Scores: [0.9232053422370617, 0.9415692821368948, 0.9148580968280468]
SVM Scores: [0.9666110183639399, 0.9816360601001669, 0.9549248747913188]
Random Forest Scores: [0.9365609348914858, 0.9549248747913188, 0.9282136894824707]


In [75]:
#this methode do the same as what we did above to present the best score
#each value represents the accuracy score obtained on one fold of the data
#during cross-validation.because we have used (n_splits=3)
from sklearn.model_selection import cross_val_score

In [78]:
cross_val_score(LogisticRegression(),digits.data, digits.target)


C:\Users\youne\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\youne\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92777778, 0.91666667, 0.9637883 , 0.96657382, 0.93036212])

In [79]:
cross_val_score(SVC(),digits.data, digits.target)


array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [80]:
cross_val_score(RandomForestClassifier(),digits.data, digits.target)

array([0.92222222, 0.91111111, 0.96100279, 0.96657382, 0.92479109])